import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

# Only include cough_detect submodule; xiaozhi/ is excluded (legacy cloud AI code)
EXCLUDED_SUBDIRS = ['xiaozhi']

list = os.listdir(cwd)
for item in list:
    if item in EXCLUDED_SUBDIRS:
        continue
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
