import os
from building import *

cwd  = GetCurrentDir()
path = [cwd]

# voice_assistant is a container for xiaozhi SDK
# It has no source files itself, only subdirectories
src = Glob('*.c') + Glob('*.cpp')

group = DefineGroup('voice_assistant', src, depend = [''], CPPPATH = path)

# Include xiaozhi subdirectory
list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
