import os
from building import *

cwd  = GetCurrentDir()
path = []
path += [cwd]
path += [cwd + '/3d_demo/3d_demo/sample',
         cwd + '/3d_demo/3d_demo/litegfx/adapt',
         cwd + '/3d_demo/3d_demo/litegfx/plat',
         cwd + '/3d_demo/3d_demo/litegfx/vglite/include',
         cwd + '/3d_demo/3d_demo/sample/lz4',
         cwd + '/3d_demo/3d_demo/sample/resource/AnimatedEmoji']
# Add source code
src = Glob('*.c')

group = DefineGroup('xiaozhi_ui', src, depend = [''], CPPPATH = path)

group = group + SConscript(os.path.join('3d_demo', '3d_demo', 'SConscript'))

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
